name: Security Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write
  security-events: write
  actions: read

jobs:
  tests:
    runs-on: self-hosted
    steps:
      - name: test1
        run: ls -n; pwd
      - name: test2
        run: python3 -V
