name: Security Checks

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: write
  pull-requests: write
  security-events: write
  actions: read

jobs:
  build:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ github.token }}
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: test1
        run: ls
      - name: test2
        run: python3 -V
